language: python

matrix:
  fast_finish: true

script:
  - echo "Hello from Travis CI!"
  - "cat ~/build.sh"
  - "cat /proc/sys/kernel/perf_event_paranoid"
  - "echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid"
  - "cat /proc/sys/kernel/perf_event_paranoid"

os:
  - linux
  - osx
